/**
 * PLANIX AI CENTRAL API ROUTER
 * Natural Language Routine Generator, AI Prediction Engine, Chat Assistant & Goal Planner
 */

const express = require('express');
const router = express.Router();
const aiService = require('../services/aiService');
const predictionService = require('../services/predictionService');
const storageService = require('../db/storageService');

// POST /api/ai/parse-routine
router.post('/parse-routine', async (req, res) => {
  try {
    const { text } = req.body;
    if (!text || !text.trim()) {
      return res.status(400).json({ success: false, error: 'Text prompt is required' });
    }
    const result = await aiService.parseRoutineSchedule(text);
    res.json({ success: true, ...result });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// POST /api/ai/bulk-add-routines
router.post('/bulk-add-routines', async (req, res) => {
  try {
    const { routines } = req.body;
    if (!Array.isArray(routines) || routines.length === 0) {
      return res.status(400).json({ success: false, error: 'Routines array required' });
    }

    const tasks = storageService.read('tasks');
    const created = [];

    for (const r of routines) {
      if (!r.text || !r.text.trim()) continue;
      const task = {
        id: `task_${Date.now()}_${Math.random().toString(36).slice(2, 5)}`,
        text: r.text.trim(),
        completed: false,
        priority: r.priority || 'medium',
        category: r.category || aiService.autoTag(r.text),
        type: 'routine',
        routineConfig: {
          time: r.routineConfig?.time || '08:00',
          repeat: r.routineConfig?.repeat || ['daily'],
          duration: r.routineConfig?.duration || 60,
          autoGenerated: true,
        },
        streak: 0,
        lastCompletedDate: null,
        suggestions: await aiService.getSuggestions(r.text),
        createdAt: new Date().toISOString(),
      };

      tasks.unshift(task);
      created.push(task);
    }

    storageService.write('tasks', tasks);
    res.status(201).json({ success: true, created });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// GET /api/ai/predictions
router.get('/predictions', (req, res) => {
  try {
    const predictions = predictionService.generatePredictions();
    res.json({ success: true, predictions });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// POST /api/ai/chat
router.post('/chat', async (req, res) => {
  try {
    const { prompt } = req.body;
    const tasks = storageService.read('tasks');
    const notes = storageService.read('notes');
    const habits = storageService.read('habits');

    const reply = await aiService.processChat(prompt || '', { tasks, notes, habits });
    res.json({ success: true, reply });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// POST /api/ai/second-brain-search
router.post('/second-brain-search', (req, res) => {
  try {
    const { query } = req.body;
    const notes = storageService.read('notes');
    const tasks = storageService.read('tasks');
    const journal = storageService.read('journal');

    const results = aiService.searchSecondBrain(query || '', { notes, tasks, journal });
    res.json({ success: true, query, memoryResults: results });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// POST /api/ai/generate-roadmap
router.post('/generate-roadmap', (req, res) => {
  try {
    const { goal } = req.body;
    const phases = aiService.generateRoadmap(goal || '');
    res.json({ success: true, goal, phases });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
