/**
 * PLANIX TASKS API ROUTER
 * CRUD operations for tasks, subtasks, kanban states, streak updates
 */

const express = require('express');
const router = express.Router();
const storageService = require('../db/storageService');
const aiService = require('../services/aiService');

function todayStr() {
  return new Date().toISOString().slice(0, 10);
}

function yesterdayStr() {
  return new Date(Date.now() - 86400000).toISOString().slice(0, 10);
}

// Auto-generate daily instances for active routines
function generateDailyPlan(tasks) {
  const today = todayStr();
  const routines = tasks.filter(t => t.type === 'routine');
  const instances = tasks.filter(t => t.type === 'routine_instance');
  let changed = false;

  for (const routine of routines) {
    const exists = instances.some(i => i.routineParentId === routine.id && i.scheduledDate === today);
    if (!exists) {
      tasks.push({
        id: `rinst_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
        text: routine.text,
        completed: false,
        priority: routine.priority || 'medium',
        category: routine.category || 'personal',
        type: 'routine_instance',
        routineParentId: routine.id,
        scheduledDate: today,
        routineConfig: routine.routineConfig,
        suggestions: routine.suggestions || [],
        createdAt: new Date().toISOString(),
      });
      changed = true;
    }
  }

  if (changed) storageService.write('tasks', tasks);
  return tasks;
}

// GET /api/tasks
router.get('/', (req, res) => {
  try {
    let tasks = storageService.read('tasks');
    tasks = generateDailyPlan(tasks);
    res.json({ success: true, tasks });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// POST /api/tasks
router.post('/', async (req, res) => {
  try {
    const { text, priority, category, type, routineConfig, subtasks, deadline } = req.body;
    if (!text || !text.trim()) {
      return res.status(400).json({ success: false, error: 'Task text is required' });
    }

    const newTask = {
      id: `task_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
      text: text.trim(),
      completed: false,
      priority: priority || 'medium',
      category: category || aiService.autoTag(text),
      type: type || 'task',
      kanbanStatus: 'todo', // 'todo' | 'in_progress' | 'review' | 'done'
      deadline: deadline || null,
      subtasks: subtasks || [],
      createdAt: new Date().toISOString(),
    };

    if (type === 'routine') {
      newTask.routineConfig = {
        time: routineConfig?.time || '08:00',
        repeat: routineConfig?.repeat || ['daily'],
        duration: routineConfig?.duration || 60,
        autoGenerated: routineConfig?.autoGenerated || false,
      };
      newTask.streak = 0;
      newTask.lastCompletedDate = null;
    }

    newTask.suggestions = await aiService.getSuggestions(text);

    const tasks = storageService.read('tasks');
    tasks.unshift(newTask);
    storageService.write('tasks', tasks);

    res.status(201).json({ success: true, task: newTask });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// PUT /api/tasks/:id
router.put('/:id', (req, res) => {
  try {
    const tasks = storageService.read('tasks');
    const idx = tasks.findIndex(t => t.id === req.params.id);
    if (idx === -1) return res.status(404).json({ success: false, error: 'Task not found' });

    Object.assign(tasks[idx], req.body);

    // Update streak for routines
    if (tasks[idx].type === 'routine' && req.body.completed !== undefined) {
      const today = todayStr();
      const yesterday = yesterdayStr();
      if (tasks[idx].completed) {
        if (tasks[idx].lastCompletedDate !== today) {
          tasks[idx].streak = (tasks[idx].lastCompletedDate === yesterday) ? (tasks[idx].streak || 0) + 1 : 1;
          tasks[idx].lastCompletedDate = today;
        }
      }
    }

    storageService.write('tasks', tasks);
    res.json({ success: true, task: tasks[idx] });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// DELETE /api/tasks/:id
router.delete('/:id', (req, res) => {
  try {
    let tasks = storageService.read('tasks');
    const idx = tasks.findIndex(t => t.id === req.params.id);
    if (idx === -1) return res.status(404).json({ success: false, error: 'Task not found' });

    const removed = tasks[idx];
    tasks = tasks.filter(t => t.id !== req.params.id && t.routineParentId !== removed.id);
    storageService.write('tasks', tasks);

    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
